namespace WYD.Frame.Services.Common;

public enum AreaNames
{
    Armia,
    Noatun,
    Azran,
    Erion,
    Gelo,
    Campo_Armia,
    Campo_Armia_2,
    Campo_Armia_3,
    Campo_Azran_1,
    Campo_Azran_2,
    Campo_Azran_3,
    Campo_Azran_4,
    Campo_Azran_5,
    Campo_Erion,
    Campo_Erion_2,
    Campo_Erion_3,
    Deserto,
    Reinos,
    Quest_Coveiro,
    Quest_Hydra,
    Quest_Kyzen,
    Quest_Gargula,
    Quest_Elfos,
    Quest_LanN,
    Quest_LanM,
    Quest_LanA,
    Campo_Gelo,
    Area_Inicial,
    Dungeon_Primeiro_Andar_1,
    Dungeon_Primeiro_Andar_2,
    Dungeon_Primeiro_Andar_3,
    Dungeon_Primeiro_Andar_4,
    Dungeon_Primeiro_Andar_5,
    Dungeon_Primeiro_Andar_6,
    Dungeon_Segundo_Andar_1,
    Dungeon_Segundo_Andar_2,
    Dungeon_Segundo_Andar_3,
    Dungeon_Segundo_Andar_4,
    Dungeon_Terceiro_Andar_1,
    Evento,
    Evento_Inicio,
    Evento_Ponte,
    
    Submundo_Primeiro_Andar_1,
    Submundo_Primeiro_Andar_2,
    Submundo_Primeiro_Andar_3,
    Submundo_Primeiro_Andar_4,
    Submundo_Segundo_Andar_1,

    Agua_N,
    Agua_M,
    Agua_A,
    
    Kefra_1,
    Kefra_2,
    Kefra_3,
    Kefra_4,
    Kefra_5,
    Kefra_6,
    Kefra_Boss,
    Uxmal,
    Pista_0,
    Pista_1,
    Pista_2,
    Pista_3,
    Pista_4,
    Pista_5,
    Pista_6,
}

public enum AreaType
{
    City,
    Camp,
    Dungeon,
    Quest,
    Submundo
}